version: "3.9"
services:
  restaurants-service:
    build: ./restaurants-service/
    ports:
    - 8081:8081
  delivery-service:
    build: ./delivery-service/
    ports:
    - 8082:8082
  foodtech-api-facade:
    build: ./foodtech-api-facade/
    depends_on:
      - "mongo"
    ports:
    - 8080:8080
    - 9090:9090
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
    - /var/mongo:/data/db
    ports:
    - 27017:27017