spring:
  data:
    mongodb:
      host: mongo
      username: root
      password: rootpassword
      authentication-database: admin

server:
  tomcat:
    max-threads: 100

logging:
  level:
    org:
      springframework:
        web:
          client: TRACE